---

services: docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

jobs:
  include:
    - stage: build and push docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $DOCKER_USERNAME/molecule-centos7:latest .
        - docker images
        - docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro $DOCKER_USERNAME/molecule-centos7:latest
        - docker exec --tty test-container env TERM=xterm ansible --version
        - docker push $DOCKER_USERNAME/molecule-centos7:latest
      if:
        - branch = master

...
